@baseUrl = http://localhost:3000

### Listar personajes (sin token - debe dar 401)
GET {{baseUrl}}/characters
Accept: application/json

### Ruta no existente (prueba de errores con el contrato API)
GET {{baseUrl}}/characters-not-found
Accept: application/json

### Atacar personaje (caso correcto)
POST {{baseUrl}}/characters/attack
Content-Type: application/json
Accept: application/json

{
  "attackerId": 1,
  "targetId": 2
}

### Atacar personaje (error: mismo atacante y objetivo)
POST {{baseUrl}}/characters/attack
Content-Type: application/json
Accept: application/json

{
  "attackerId": 1,
  "targetId": 1
}

### Atacar personaje (error: atacante no existe)
POST {{baseUrl}}/characters/attack
Content-Type: application/json
Accept: application/json

{
  "attackerId": 999,
  "targetId": 2
}

### Resetear HP de todos los personajes
POST {{baseUrl}}/characters/reset
Accept: application/json

### Registro de usuario
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "user1@batalla.com",
  "password": "123456"
}

### Login de usuario
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "user1@batalla.com",
  "password": "123456"
}

### Listar personajes (con token - preparado para JwtAuthGuard)
GET {{baseUrl}}/characters
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}

### Atacar personaje (con token - preparado para JwtAuthGuard)
POST {{baseUrl}}/characters/attack
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}

{
  "attackerId": 1,
  "targetId": 2
}

### Atacar personaje (error de validación DTO)
POST {{baseUrl}}/characters/attack
Content-Type: application/json
Accept: application/json

{
  "attackerId": 1,
  "targetId": 2,
  "extraField": true
}

### Resetear HP (USER -> debe dar 403)
POST {{baseUrl}}/characters/reset
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}


### Login admin (necesita usuario admin en seeds)
# @name loginAdmin
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@batalla.com",
  "password": "123456"
}

### Resetear HP (ADMIN -> debe funcionar)
POST {{baseUrl}}/characters/reset
Accept: application/json
Authorization: Bearer {{loginAdmin.response.body.data.access_token}}

### Iniciar batalla PVE (USER o ADMIN)
# @name startPve
POST {{baseUrl}}/battles/start/pve
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}

{
  "myCharacterId": 7,
  "machineCharacterId": 8
}

### Iniciar batalla PVP (USER o ADMIN)
# @name startPvp
POST {{baseUrl}}/battles/start/pvp
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}

{
  "opponentUserId": 2,
  "myCharacterId": 7,
  "opponentCharacterId": 11
}

### Obtener batalla PVE por id
GET {{baseUrl}}/battles/{{startPve.response.body.data.battleId}}
Accept: application/json
Authorization: Bearer {{login.response.body.data.access_token}}
